# Generated by Django 2.2.3 on 2019-07-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Text',
        ),
    ]
